### ISSUE TITLE
Is flamer-motion devDependencies?

### ISSUE THREAD

**Issue by kjkandrea** [Temzasse/react-modal-sheet#106]
I use a storybook.
I tried to write a story of a component that uses react-modal-sheet.

And I encountered the error.

```bash
Unexpected error while loading ./components/atom/BottomSheet/BottomSheet.stories.tsx: Cannot find module 'framer-motion'
 Error: Cannot find module 'framer-motion'
    at webpackMissingModule (http://localhost:6006/vendors-_yarn___virtual___pmmmwh-react-refresh-webpack-plugin-virtual-01ef1f374d_0_cache_pmmm-b6173b.iframe.bundle.js:56428:50)
    at ../../../.yarn/__virtual__/react-modal-sheet-virtual-3527c04fec/0/cache/react-modal-sheet-npm-1.8.1-7662934411-06780ede10.zip/node_modules/react-modal-sheet/dist/react-modal-sheet.esm.js (http://localhost:6006/vendors-_yarn___virtual___pmmmwh-react-refresh-webpack-plugin-virtual-01ef1f374d_0_cache_pmmm-b6173b.iframe.bundle.js:56428:138)
    at options.factory (http://localhost:6006/runtime~main.iframe.bundle.js:682:31)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:339:21)
    at ./src/components/atom/BottomSheet/BottomSheet.tsx (http://localhost:6006/main.iframe.bundle.js:6450:75)
    at options.factory (http://localhost:6006/runtime~main.iframe.bundle.js:682:31)
    at __webpack_require__ (http://localhost:6006/runtime~main.iframe.bundle.js:28:33)
    at fn (http://localhost:6006/runtime~main.iframe.bundle.js:339:21)
    at ./src/components/atom/BottomSheet/BottomSheet.stories.tsx (http://localhost:6006/main.iframe.bundle.js:21:98)
```

And I found framer-motion in devDependency of react-modal-sheet.

I tried installing it on my app. `yarn add framer-motion`.
now error disappeared when I installed it.

I don't know much about package.json's dependency management, 
but wouldn't it be right for framer-motion to be declared in dependencies?

**Comment by kjkandrea** [comment]
i use yarn.
this error was resolved using [packageExtensions](https://yarnpkg.com/configuration/yarnrc#packageExtensions) in my project.

`.yarnrc.yml`
```yml
packageExtensions:
  react-modal-sheet@*:
    dependencies:
      framer-motion: '*'
```

If someone has a dependency problem, I hope it helps.

**Comment by Temzasse** [comment]
Framer Motion is a peer dependency so you'll have to install it to your project yourself 🙂
